[tool.poetry]
name = "testing-chat"
version = "0.1.0"
description = ""
authors = ["NivNavick <nnavick@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pdfreader = "^0.1.15"
pandas = "^2.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
